[2.3] pap,papstatus:  changes to allow Imagewriters to print, and nicer status messages
Netatalk/netatalk pull request #722
Opened 2024-02-21 12:45 UTC by nutzman

Based on code from kakwa - https://github.com/kakwa/image-writer/tree/master/bin/pap

2024-02-21 18:13 UTC, NJRoadfan commented on bin/pap/pap.c
> +#define IMAGEWRITER "ImageWriter"
This will not work with the ImageWriter LQ as its NBP Type is "LQ".

2024-02-21 18:17 UTC, NJRoadfan requested changes
The papstatus program needs to be updated with conditionals checking for NBP type of "ImageWriter" or "LQ" and their special status bytes be processed when one is detected. Normally LaserWriters send back a 255 character Pascal style string with a status message, while the ImageWriters send back a raw 2-byte value.

2024-02-25 11:37 UTC, rdmark commented on bin/pap/pap.c
> +	int		is_imagewriter;
Nitpick, but indentation should be four spaces and not a tab here.

In fairness, the indentation can be a bit all over the place in this codebase. But let's use the same indentation as neighboring code to maintain readability.

2024-02-25 11:37 UTC, rdmark commented on bin/pap/pap.c
> +		0 == strcmp(IMAGEWRITER_LQ, type)  );
indentation

2024-02-25 11:37 UTC, rdmark commented on bin/pap/pap.c
> +		 * The Imagewriter II doesn't handle this well, either
indentation

2024-02-25 11:37 UTC, rdmark commented on bin/pap/papstatus.c
> +		0 == strcmp(IMAGEWRITER_LQ, type)  );
indentation

2024-02-25 13:38 UTC, nutzman commented
I updated my changes to use spaces. I could format the entire files if you like.

2024-02-27 03:58 UTC, rdmark approved these changes

2024-02-27 03:58 UTC, merged

2024-02-27 03:59 UTC, rdmark commented
Thanks again for your contribution! My HP DeskWriter 550C with LocalTalk / PAP support was delivered yesterday, but I didn't have a chance to unpack and set it up yet. I'm looking forward to playing around with `pap` and `papstatus` soon!